### ISSUE TITLE
Prefix all models with Sphere

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-jvm-sdk#182]
Currently JVM returns for example products of type ```Product```. As JVM user you would most probably want to extend or wrap this type and add some helper methods. New model would need new name i.e: ```StandardProduct```. If you build many JVM based projects you would want to have sphere-jvm-sdk-commons library which provides ```StandardProduct``` with most common helpers/methods. In your target shop/project you would use or extend ```StandardProduct``` and give new model name i.e.: ```CustomProduct```.
It would be nice if those intuitive and simple names like: Product, Customer, Cart, Price and others would not be reserved for sphere-jvm-sdk but could be used by target project "xyzShop".

Current:
```Product -> StandardProduct -> CustomProduct```
Desired:
```SphereProduct -> StandardProduct -> Product```

**Comment by lauraluiz** [comment]
If you prefix everything with Sphere_ or Standard_ in the SDK, then you won't be able to filter (in a meaningful way) anymore, as you would have everything returned. In IDEs like Eclipse you can only filter by prefix, so if you search "Product" you will not received anything from the SDK.

Also, since the project is the one extending the Product from the SDK, it makes sense to be the one extending the name as well. If you have a Product in Sphere, you want to make a class specifically for your project (e.g. MyProduct, ShopProduct...). The more specific product name (MyProduct) should be the one in the project, while the more generic should be in the SDK (Product).

It would be understandable if having to make up a specific class name would be a huge drawback, but the name is completely up to you (so you can decide the complexity and structure of it) and with all the advantages and shortcuts of an IDE it shouldn't be a problem to change it eventually if you chose wrong.
