### ISSUE TITLE
Create catchable exception when requested offset is greater than 100000

### ISSUE THREAD

**Issue by fwilk** [sphereio/sphere-jvm-sdk#198]
When you request an offset which is greater than 100000 you receive the following error:

io.sphere.sdk.client.SphereBackendException: Malformed parameter: offset: The offset parameter must be in the range of [0..100000]

This issue might rarely occur in real-life, but it would be nice to be able to catch it without parsing the response-body. Maybe the solution could be the same as in 
https://github.com/sphereio/sphere-jvm-sdk/issues/178

**Comment by schleichardt** [comment]
In #178 the SPHERE.IO response was not mapped accordingly, the SDK throw an unmappable Exception, but the API returned an empty result.

Here is the API throwing the error. Since I know before sending the request that it never will be answered with the expected objects, I can throw a subclass of IllegalArgumentException while setting an invalid offset parameter, no need to send the request.

**Comment by schleichardt** [comment]
I don't want to return an empty result list since it would kind of swallow the problem.

**Comment by butenkor** [comment]
Just curious. Why API is throwing error?

**Comment by emmenko** [comment]
@butenkor we have a constraint on the max offset allowed, that's why the API will throw if the max value is exceeded. 
The thing is that using a large offset is an expensive operation which is inefficient and CPU intensive and that should be avoided. 

http://docs.mongodb.org/manual/reference/method/cursor.skip/
http://openmymind.net/Paging-And-Ranking-With-Large-Offsets-MongoDB-vs-Redis-vs-Postgresql/

Also you usually don't need to fetch with such large offsets, if so then you are doing something wrong with your application. Example: you have like 1M orders. Are you going to "manually" scroll through all pages or are you going to narrow your results first? Same thing with a google search: you usually look at the first page result, max 2nd and 3rd page but not more.

PS: also I agree with @schleichardt about throwing instead of sending the request

**Comment by butenkor** [comment]
@emmenko Thanks for the info.
