### ISSUE TITLE
ProductDeleteByIdCommand.of() takes only objects of type Product as parameter

### ISSUE THREAD

**Issue by MeiSign** [sphereio/sphere-jvm-sdk#236]
Is there a way to pass only an id instead of a whole product to the of method of the ProductDeleteByIdCommand?
In some cases it would be much easier to just pass an Id and delete a product by id. 
For example if I cache products that should be deleted in the future and don't want to save the whole products but a list of their identifiers.
Otherwise the classname is misleading in my opinion.

**Comment by schleichardt** [comment]
http://sphereio.github.io/sphere-jvm-sdk/javadoc/master/io/sphere/sdk/products/commands/ProductDeleteByIdCommand.html#of-io.sphere.sdk.models.Versioned- takes `Versioned<Product>` as parameter, so you can pass a product or you provide a `Versioned` directly with http://sphereio.github.io/sphere-jvm-sdk/javadoc/master/io/sphere/sdk/models/Versioned.html#of-java.lang.String-long-:

```
final String id = "abc";
final long version = 1L;
final Versioned<Product> product =Versioned.<Product>of(id, version);
```
Storing the product identifiers is not enough, since you need the version.

**Comment by MeiSign** [comment]
That is exactly what I was looking for, thanks a lot :)
