### ISSUE TITLE
provide a solution if fields not implemented in the SDK model

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#253]
for example in the SPHERE.IO backend appears a new field for a resource, and the SDK has it not jet and it is not accessible

**Comment by schleichardt** [comment]
Here is a draft, but I am currently working on testing it:

https://gist.github.com/schleichardt/bbf97ffbd4eb64fdb0c5

**Comment by abrauner** [comment]
Hey there, the Issue poped up again on our side after we postponed it a few days. The concrete problem is that we'd like to change the State of a LineItem. Therefore we need the current State and the possible transitions. 
The problem is that the ItemState only contains a quantity and not even a referece to a State. There is a short TODO note to add this. But there is not even a State-Model to reference to in the SDK when I'm right. I'd like to support on this issue but I might need some "getting started" help. 
So questions would be: 
Is there another (more general) State than ItemState or is this to be created?

Would it be the right approach to 
- Add State into the models package,
- add a StateQuery, StateQueryModel,  StateEndpoint, 
- adding the Reference to a State into the ItemState
- adding TransitionLineItemState as updateAction
?

Thanks for your help.

Cheers Ansgar

**Comment by schleichardt** [comment]
Yes, there is a TODO note, I did not want to introduce something which is not tested.

Looks good.
* I would expect a State interface as io.sphere.sdk.states.State 
* StateQueryModel is not mandatory
* Yes: adding the Reference to a State into the ItemState
* Yes: adding TransitionLineItemState as updateAction ?

**Comment by abrauner** [comment]
Something like this: 
https://github.com/abrauner/sphere-jvm-sdk/compare/feature/state-and-item-state-queries

**Comment by abrauner** [comment]
I will work on other queries and commands and add them here too. Maybe we get a good start for this topic here and can integrate it soon. Changes from review should be covered already.

**Comment by schleichardt** [comment]
won't fix
