### ISSUE TITLE
Reference expansion for product projection search

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#604]

**Comment by schleichardt** [comment]
@lauraluiz Can you extract an interface for SearchModelImpl and hide the impl in package scope?

**Comment by lauraluiz** [comment]
I cannot make SearchModelImpl package-scope because it is used from `io.sphere.sdk.products.search.ProductDataSearchModelBase` in the models sub-module. And it already has a interface, that's why it is called `Impl` :P

**Comment by schleichardt** [comment]
You could move `SearchModelImpl` to `io.sphere.sdk.products.search`. I am not sure if we need search related stuff outside of products.

**Comment by lauraluiz** [comment]
I agree with the change, but before we have to check how to do this in the Query side, because in the end it is where I adapted it from. Take a look at the classes `io.sphere.sdk.products.queries.ProductDataQueryModelBase` and `io.sphere.sdk.queries.DefaultModelQueryModelImpl`, it is the equivalent for Search.

**Comment by lauraluiz** [comment]
The only difference, as you can see, is that Search do not need a DefaultModel, so it uses directly the SearchModelImpl.

**Comment by schleichardt** [comment]
Hmm, I would say we merge it as it is and and I will have a closer look then.

**Comment by schleichardt** [comment]
https://github.com/sphereio/sphere-jvm-sdk/pull/624
