### ISSUE TITLE
TaxCategoryDraft should allow tax category creation without rates

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-jvm-sdk#806]
Its not documented exactly as Optional in the doc: http://dev.sphere.io/http-api-projects-taxCategories.html#create-tax-category
but using API directly one can create new category providing only the name:
```
  {
      "name": "myTaxTest1"
  }
```
In JVM would be:
```
TaxCategoryDraft.of(name)
```

**Comment by schleichardt** [comment]
not necessary: provide an empty tax rate list with http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M19/io/sphere/sdk/taxcategories/TaxCategoryDraft.html#of-java.lang.String-java.util.List-

I think it is a good practice to courage the SDK user to create a tax category with tax rates since without it is not really usable.

I should write a test if the method works with an empty list.

**Comment by butenkor** [comment]
@schleichardt Yes i used it with empty list and it works. I think you may be right that in most scenarios it should not be empty but i actually had a real case where tax categories (as also rates) were not required as all items and also delivery should have cost exactly 0. 
I thought that SDK represents exactly API documentation therefore i created an issue. Its not really an issue as it works with empty list its just not intuitive.

**Comment by schleichardt** [comment]
I will add some documentation - so it was good that you reported it. Yes, the SDK should be API near but I want prevent developers as often as possible to do sth. wrong or forget stuff.
